-- ============================================
-- Hold Your Own Brand - Initial Database Schema
-- Migration: 001_initial_schema.sql
-- 
-- This migration creates all the core tables needed for the e-commerce platform.
-- Tables are created in dependency order (referenced tables first).
-- ============================================

-- Enable UUID extension for generating unique identifiers
-- UUIDs are better than sequential IDs because they:
-- 1. Don't reveal how many records exist
-- 2. Can be generated by clients without hitting the database
-- 3. Are globally unique across all tables
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- USERS TABLE
-- ============================================
-- Stores all user accounts (customers and admins)
-- The role field determines what the user can do in the system

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    
    -- Role determines access level:
    -- 'customer' - Regular shoppers
    -- 'admin' - Can manage products, orders, etc.
    -- 'super_admin' - Full system access including user management
    role VARCHAR(20) NOT NULL DEFAULT 'customer' 
        CHECK (role IN ('customer', 'admin', 'super_admin')),
    
    is_active BOOLEAN NOT NULL DEFAULT true,
    email_verified BOOLEAN NOT NULL DEFAULT false,
    
    -- Timestamps for tracking
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login TIMESTAMP WITH TIME ZONE
);

-- Index on email for fast login lookups
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

-- ============================================
-- REFRESH TOKENS TABLE
-- ============================================
-- Stores refresh tokens for JWT authentication
-- We store these so we can invalidate them when users log out

CREATE TABLE refresh_tokens (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL,  -- SHA-256 hash of the token
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,  -- NULL if token is still valid
    user_agent TEXT,  -- Browser/device info for security tracking
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_hash ON refresh_tokens(token_hash);

-- ============================================
-- PASSWORD RESETS TABLE
-- ============================================
-- Stores password reset tokens

CREATE TABLE password_resets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,  -- NULL if not yet used
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_password_resets_token ON password_resets(token_hash);

-- ============================================
-- ADDRESSES TABLE
-- ============================================
-- Stores shipping and billing addresses for users
-- Users can have multiple saved addresses

CREATE TABLE addresses (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,  -- NULL for guest checkout
    
    -- Address type helps users organize their addresses
    address_type VARCHAR(20) NOT NULL DEFAULT 'shipping'
        CHECK (address_type IN ('shipping', 'billing', 'both')),
    
    -- Contact info
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    company VARCHAR(100),
    phone VARCHAR(20),
    
    -- Address fields
    street_address_1 VARCHAR(255) NOT NULL,
    street_address_2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(2) NOT NULL DEFAULT 'US',  -- ISO 3166-1 alpha-2
    
    is_default BOOLEAN NOT NULL DEFAULT false,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_addresses_user ON addresses(user_id);

-- ============================================
-- CATEGORIES TABLE
-- ============================================
-- Product categories with support for subcategories (hierarchy)

CREATE TABLE categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,  -- URL-friendly name (e.g., "mens-tees")
    description TEXT,
    image_url VARCHAR(500),
    
    -- For subcategories: NULL means top-level category
    parent_id UUID REFERENCES categories(id) ON DELETE SET NULL,
    
    -- Controls display order in navigation
    sort_order INTEGER NOT NULL DEFAULT 0,
    
    is_active BOOLEAN NOT NULL DEFAULT true,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_categories_slug ON categories(slug);
CREATE INDEX idx_categories_parent ON categories(parent_id);

-- ============================================
-- PRODUCTS TABLE
-- ============================================
-- Main product catalog

CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
    
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    
    -- Pricing
    price DECIMAL(10, 2) NOT NULL,
    compare_at_price DECIMAL(10, 2),  -- Original price for showing "was $X, now $Y"
    
    -- SEO
    meta_title VARCHAR(100),
    meta_description VARCHAR(300),
    
    -- Product status
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'active', 'archived')),
    
    -- Feature flags
    is_featured BOOLEAN NOT NULL DEFAULT false,
    is_new BOOLEAN NOT NULL DEFAULT false,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_products_slug ON products(slug);
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_status ON products(status);
CREATE INDEX idx_products_featured ON products(is_featured) WHERE is_featured = true;

-- ============================================
-- PRODUCT IMAGES TABLE
-- ============================================
-- Multiple images per product

CREATE TABLE product_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(255),
    
    -- First image (sort_order = 0) is the primary/thumbnail image
    sort_order INTEGER NOT NULL DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_product_images_product ON product_images(product_id);

-- ============================================
-- PRODUCT VARIANTS TABLE
-- ============================================
-- Size/color combinations with their own SKUs and inventory

CREATE TABLE product_variants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    -- SKU must be unique across all products
    sku VARCHAR(100) NOT NULL UNIQUE,
    
    -- Variant attributes (e.g., "Large", "Black")
    size VARCHAR(50),
    color VARCHAR(50),
    
    -- Variant-specific pricing (NULL means use product price)
    price_adjustment DECIMAL(10, 2) DEFAULT 0,
    
    -- Inventory
    quantity INTEGER NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER NOT NULL DEFAULT 5,
    
    -- Can be set to false to hide out-of-stock variants
    is_active BOOLEAN NOT NULL DEFAULT true,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_variants_product ON product_variants(product_id);
CREATE INDEX idx_variants_sku ON product_variants(sku);

-- ============================================
-- DISCOUNT CODES TABLE
-- ============================================
-- Promotional codes for cart discounts

CREATE TABLE discount_codes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    code VARCHAR(50) NOT NULL UNIQUE,  -- e.g., "SUMMER20"
    description TEXT,
    
    -- Discount type and value
    discount_type VARCHAR(20) NOT NULL
        CHECK (discount_type IN ('percentage', 'fixed_amount', 'free_shipping')),
    discount_value DECIMAL(10, 2) NOT NULL,  -- Percentage (0-100) or fixed amount
    
    -- Usage limits
    minimum_purchase DECIMAL(10, 2) DEFAULT 0,  -- Min cart total to use
    max_uses INTEGER,  -- NULL = unlimited
    max_uses_per_customer INTEGER DEFAULT 1,
    current_uses INTEGER NOT NULL DEFAULT 0,
    
    -- Validity period
    starts_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,  -- NULL = never expires
    
    is_active BOOLEAN NOT NULL DEFAULT true,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_discount_codes_code ON discount_codes(code);

-- ============================================
-- CARTS TABLE
-- ============================================
-- Shopping carts (for both guests and logged-in users)

CREATE TABLE carts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,  -- NULL for guests
    
    -- Session ID for guest carts (stored in browser)
    session_id VARCHAR(100),
    
    -- Applied discount code
    discount_code_id UUID REFERENCES discount_codes(id) ON DELETE SET NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Either user_id or session_id must be present
    CONSTRAINT cart_owner CHECK (user_id IS NOT NULL OR session_id IS NOT NULL)
);

CREATE INDEX idx_carts_user ON carts(user_id);
CREATE INDEX idx_carts_session ON carts(session_id);

-- ============================================
-- CART ITEMS TABLE
-- ============================================
-- Items in a shopping cart

CREATE TABLE cart_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    cart_id UUID NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    variant_id UUID NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Prevent duplicate items (same variant in same cart)
    UNIQUE(cart_id, variant_id)
);

CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);

-- ============================================
-- ORDERS TABLE
-- ============================================
-- Completed orders

CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,  -- Keep orders if user deleted
    
    -- Order number (human-readable, for customer service)
    order_number VARCHAR(20) NOT NULL UNIQUE,
    
    -- Order status workflow
    status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (status IN (
            'pending',      -- Just placed, awaiting payment
            'paid',         -- Payment received
            'processing',   -- Being prepared for shipment
            'shipped',      -- Handed off to carrier
            'delivered',    -- Confirmed delivered
            'cancelled',    -- Order cancelled
            'refunded'      -- Money returned
        )),
    
    -- Payment info
    payment_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded', 'partially_refunded')),
    payment_method VARCHAR(50),  -- 'stripe', 'paypal', etc.
    stripe_payment_intent_id VARCHAR(255),
    
    -- Pricing breakdown
    subtotal DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    shipping_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total DECIMAL(10, 2) NOT NULL,
    
    -- Applied discount code (for reference)
    discount_code VARCHAR(50),
    
    -- Addresses (stored as JSON to preserve historical data)
    shipping_address JSONB NOT NULL,
    billing_address JSONB NOT NULL,
    
    -- Shipping info
    shipping_method VARCHAR(50),
    tracking_number VARCHAR(100),
    tracking_url VARCHAR(500),
    
    -- Customer contact (in case they're a guest)
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    
    -- Notes
    customer_notes TEXT,  -- Special instructions from customer
    admin_notes TEXT,     -- Internal notes
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    shipped_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_number ON orders(order_number);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

-- ============================================
-- ORDER ITEMS TABLE
-- ============================================
-- Line items within an order
-- We store price at time of purchase in case prices change later

CREATE TABLE order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    
    -- Reference to the product (may be deleted, so we store details)
    product_id UUID REFERENCES products(id) ON DELETE SET NULL,
    variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,
    
    -- Stored product info (preserved even if product changes/deleted)
    product_name VARCHAR(255) NOT NULL,
    variant_name VARCHAR(100),  -- e.g., "Large / Black"
    sku VARCHAR(100) NOT NULL,
    
    -- Pricing at time of order
    unit_price DECIMAL(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    
    -- Product image at time of order
    image_url VARCHAR(500),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_order_items_order ON order_items(order_id);

-- ============================================
-- WISHLISTS TABLE
-- ============================================
-- User saved products (favorites)

CREATE TABLE wishlists (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Each user can only wishlist a product once
    UNIQUE(user_id, product_id)
);

CREATE INDEX idx_wishlists_user ON wishlists(user_id);

-- ============================================
-- INVENTORY LOG TABLE
-- ============================================
-- Track all inventory changes for auditing

CREATE TABLE inventory_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    variant_id UUID NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    
    -- Change details
    quantity_change INTEGER NOT NULL,  -- Positive for additions, negative for subtractions
    previous_quantity INTEGER NOT NULL,
    new_quantity INTEGER NOT NULL,
    
    -- Reason for change
    reason VARCHAR(50) NOT NULL
        CHECK (reason IN ('sale', 'restock', 'adjustment', 'return', 'damaged', 'manual')),
    
    -- Related order (if applicable)
    order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
    
    -- Who made the change
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_inventory_log_variant ON inventory_log(variant_id);
CREATE INDEX idx_inventory_log_created ON inventory_log(created_at DESC);

-- ============================================
-- AUDIT LOG TABLE
-- ============================================
-- Track admin actions for security and debugging

CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    
    action VARCHAR(100) NOT NULL,  -- e.g., 'product.create', 'order.status_change'
    entity_type VARCHAR(50) NOT NULL,  -- e.g., 'product', 'order', 'user'
    entity_id UUID,
    
    -- Store the changes made (old and new values)
    changes JSONB,
    
    ip_address VARCHAR(45),
    user_agent TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_audit_log_user ON audit_log(user_id);
CREATE INDEX idx_audit_log_entity ON audit_log(entity_type, entity_id);
CREATE INDEX idx_audit_log_created ON audit_log(created_at DESC);

-- ============================================
-- NEWSLETTER SUBSCRIBERS TABLE
-- ============================================
-- Email list for marketing

CREATE TABLE newsletter_subscribers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    
    first_name VARCHAR(50),
    
    is_active BOOLEAN NOT NULL DEFAULT true,
    
    -- Track how they subscribed
    source VARCHAR(50) DEFAULT 'website',  -- 'website', 'checkout', 'popup', etc.
    
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    unsubscribed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_newsletter_email ON newsletter_subscribers(email);

-- ============================================
-- FUNCTION: Update timestamp trigger
-- ============================================
-- Automatically update the updated_at column when a row is modified

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply the trigger to all tables with updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_addresses_updated_at BEFORE UPDATE ON addresses
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_variants_updated_at BEFORE UPDATE ON product_variants
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_discount_codes_updated_at BEFORE UPDATE ON discount_codes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_carts_updated_at BEFORE UPDATE ON carts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_cart_items_updated_at BEFORE UPDATE ON cart_items
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- FUNCTION: Generate order number
-- ============================================
-- Creates human-readable order numbers like "HYOW-20260201-0001"

CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS VARCHAR(20) AS $$
DECLARE
    date_part VARCHAR(8);
    seq_part VARCHAR(4);
    new_order_number VARCHAR(20);
BEGIN
    -- Get today's date in YYYYMMDD format
    date_part := TO_CHAR(NOW(), 'YYYYMMDD');
    
    -- Count orders today and add 1
    SELECT LPAD((COUNT(*) + 1)::TEXT, 4, '0')
    INTO seq_part
    FROM orders
    WHERE DATE(created_at) = CURRENT_DATE;
    
    new_order_number := 'HYOW-' || date_part || '-' || seq_part;
    
    RETURN new_order_number;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- SEED INITIAL ADMIN USER
-- ============================================
-- Create the super admin account for Tzvetomir
-- Password should be changed immediately after first login!
-- Default password: ChangeMe123! (bcrypt hash below)

INSERT INTO users (email, password_hash, first_name, last_name, role, email_verified)
VALUES (
    'tzvtdr@gmail.com',
    -- Hash for 'ChangeMe123!' - CHANGE THIS IMMEDIATELY
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.aKqoHQYr5FkwKO',
    'Tzvetomir',
    'Todorov',
    'super_admin',
    true
);

-- ============================================
-- SEED INITIAL CATEGORIES
-- ============================================

INSERT INTO categories (name, slug, description, sort_order) VALUES
('T-Shirts', 'tees', 'Premium quality streetwear tees', 1),
('Hoodies', 'hoodies', 'Heavyweight hoodies for the streets', 2),
('Hats', 'hats', 'Caps, beanies, and headwear', 3),
('Accessories', 'accessories', 'Complete the look', 4);

-- Success message
DO $$
BEGIN
    RAISE NOTICE '✅ Initial schema created successfully!';
    RAISE NOTICE '⚠️  Remember to change the admin password immediately!';
END $$;
